#!/bin/bash

port=8888
wp=/web_share
public_ip=

change_port() {
    echo
    read -p "请输入端口：" input_info
    [ -z "$input_info" ] && pannel
    sed -i "s|^port=.*|port=$input_info|" /bin/dlt
    port=$input_info
    pkill python3
    setsid python3 -m http.server $port > /dev/null 2>&1 &
    pannel
}

change_wp() {
    echo
    read -p "请输入路径：" input_info
    [ -z "$input_info" ] && pannel
    sed -i "s|^wp=.*|wp=$input_info|" /bin/dlt
    wp=$input_info
    cd $wp
    pkill python3
    setsid python3 -m http.server $port > /dev/null 2>&1 &
    pannel
}

aria2_download() {
    echo
    dl_connections=1
    if [ "$dlt_choice" = "5" ];then
        read -p "设置线程数[1-16]：" dl_connections
        echo
    fi
    read -p "请输入文件直链：" file_url
    echo
    [ ! -z "$file_url" ] && setsid aria2c -c -x $dl_connections -d $wp $file_url
    while [ "$(ps -ef | grep "aria2c" | grep -v "grep")" ];do
        sleep 0.1
    done
    pannel
}

youtubedl_dl() {
    echo
    read -p "设置线程数[1-16]：" dl_connections
    echo
    read -p "请输入视频网址：" file_url
    echo
    [ ! -z "$dl_connections" ] && [ ! -z "$file_url" ] && setsid youtube-dl $file_url --external-downloader 'aria2c' --external-downloader-args "-c -x $dl_connections -d $wp"
    while [ "$(ps -ef | grep "youtube-dl" | grep -v "grep")" ];do
        sleep 0.1
    done
    pannel
}

dlt_on_off() {
    if [ -z "$(ps -ef | grep "http.server" | grep -v "grep")" ];then
        setsid python3 -m http.server $port > /dev/null 2>&1 &
    else
        kill -9 $(ps -ef | grep "http.server" | grep -v "grep" | awk '{print $2}')
    fi
    pannel
}

pannel() {
    mkdir -p $wp
    chmod -R 777 $wp
    cd $wp
    if [ -z "$(grep -Eo "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" /bin/dlt)" ];then
        public_ip=$(curl -s https://api.myip.com | grep -Eo "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*")
        sed -i 's|^public_ip=.*|public_ip='$public_ip'|' /bin/dlt
    else
        public_ip=$(grep -Eo "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" /bin/dlt)
    fi
    echo
    echo -e " 1.更改 python_http 端口 \033[33m$nginx_port\033[0m"
    echo -e " 2.更改 python_http 访问地址 \033[33m$nginx_wp\033[0m"
    [ -z "$(ps -ef | grep "http.server" | grep -v "grep")" ] && echo " 3.启动 python_http 服务"
    [ -z "$(ps -ef | grep "http.server" | grep -v "grep")" ] || echo -e " 3.停止\033[32m python_http 服务\033[0m  \033[33mhttp://${public_ip}:${port}\033[0m"
    echo -e " 4.使用aria2单线程下载文件到 \033[33m$wp\033[0m"
    echo -e " 5.使用aria2多线程下载文件到 \033[33m$wp\033[0m"
    echo -e " 6.使用youtube-dl多线程下载视频到 \033[33m$wp\033[0m"
    echo
    read -p "请选择：" dlt_choice

    [ "$dlt_choice" = "1" ] && change_port
    [ "$dlt_choice" = "2" ] && change_wp
    [ "$dlt_choice" = "3" ] && dlt_on_off
    [ "$dlt_choice" = "4" -o "$dlt_choice" = "5" ] && aria2_download
    [ "$dlt_choice" = "6" ] && youtubedl_dl
    clear && exit 0
}

pannel
