#!/bin/bash
export PATH="/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin"

if [ "$1" = "start" ];then
    iptables -t nat -I OUTPUT -p tcp --dport 80 -j REDIRECT --to 3000
    iptables -t nat -I OUTPUT -p tcp -m owner --uid-owner koolproxy_i386 -j ACCEPT
    su - koolproxy_i386 -c "/bin/v2ray/koolproxy_i386"
else
    pkill koolproxy_i386
    iptables -t nat -D OUTPUT -p tcp --dport 80 -j REDIRECT --to 3000
    iptables -t nat -D OUTPUT -p tcp -m owner --uid-owner koolproxy_i386 -j ACCEPT
fi
